group-categoryhighlight.group=Featured Categories

document1.hint=Pick a category document for the first tile.
document2.hint=Pick a category document for the second tile (optional).
document3.hint=Pick a category document for the third tile (optional).
document4.hint=Pick a category document for the fourth tile (optional).
